#!/bin/sh

tmp=$(mktemp --tmpdir --directory "jami-peer-monitor.XXXXXXXXXX")

export XDG_CONFIG_HOME="$tmp"
export XDG_CACHE_HOME="$tmp"
export XDG_DATA_HOME="$tmp"
export GUILE_AUTO_COMPILE=0
export JAMI_LOG_FILE="$1.log"

./scenario.scm $@

rm -rf "$tmp"

