static const char *x264_preset_ultrafast = "coder=0\n" \
"flags=-loop\n" \
"cmp=+chroma\n" \
"partitions=-parti8x8-parti4x4-partp8x8-partb8x8\n" \
"me_method=dia\n" \
"subq=0\n" \
"me_range=16\n" \
"g=250\n" \
"keyint_min=25\n" \
"sc_threshold=0\n" \
"i_qfactor=0.71\n" \
"b_strategy=0\n" \
"qcomp=0.6\n" \
"qmin=0\n" \
"qmax=69\n" \
"qdiff=4\n" \
"bf=0\n" \
"refs=1\n" \
"directpred=1\n" \
"trellis=0\n" \
"flags2=-bpyramid-mixed_refs-wpred-dct8x8+fastpskip-mbtree\n" \
"wpredp=0\n" \
"aq_mode=0\n" \
"rc_lookahead=0";
