---
accounts:
- alias: 100
  codecs: 0/3/8/9/110/111/112/
  credential:
  - Account.password: password
    Account.realm: '*'
    Account.username: 100
  displayName:
  dtmfType: overrtp
  enable: true
  hostname: 127.0.0.1:5062
  id: Account:1334024061
  interface: default
  mailbox:
  port: 5060
  publishAddr: 0.0.0.0
  publishPort: 5060
  registrationexpire: 600
  ringtoneEnabled: true
  ringtonePath: /usr/share/ring/ringtones/default.wav
  sameasLocal: true
  serviceRoute:
  srtp:
    enable: false
    keyExchange:
    rtpFallback: false
  stunEnabled: false
  stunServer: stun.sflphone.org
  tls:
    calist:
    certificate:
    ciphers:
    enable: false
    method: TLSv1
    password:
    privateKey:
    requireCertif: true
    server:
    timeout: 2
    tlsPort: 5061
    verifyClient: true
    verifyServer: true
  type: SIP
  updateContact: false
  username: 100
  zrtp:
    displaySas: true
    displaySasOnce: false
    helloHashEnabled: true
    notSuppWarning: true
- alias: 200
  codecs: 0/3/8/9/110/111/112/
  credential:
  - Account.password: password
    Account.realm: '*'
    Account.username: 200
  displayName:
  dtmfType: overrtp
  enable: true
  hostname: 127.0.0.1:5062
  id: Account:1334024356
  interface: default
  mailbox:
  port: 5060
  publishAddr: 0.0.0.0
  publishPort: 5060
  registrationexpire: 600
  ringtoneEnabled: true
  ringtonePath: /usr/share/ring/ringtones/default.wav
  sameasLocal: true
  serviceRoute:
  srtp:
    enable: false
    keyExchange:
    rtpFallback: false
  stunEnabled: false
  stunServer: stun.sflphone.org
  tls:
    calist:
    certificate:
    ciphers:
    enable: false
    method: TLSv1
    password:
    privateKey:
    requireCertif: true
    server:
    timeout: 2
    tlsPort: 5061
    verifyClient: true
    verifyServer: true
  type: SIP
  updateContact: false
  username: 200
  zrtp:
    displaySas: true
    displaySasOnce: false
    helloHashEnabled: true
    notSuppWarning: true
- alias:
  codecs: 0/3/8/9/110/111/112/
  credential:
  - Account.password:
    Account.realm: '*'
    Account.username:
  displayName:
  dtmfType: overrtp
  enable: true
  hostname:
  id: IP2IP
  interface: default
  mailbox:
  port: 5060
  publishAddr:
  publishPort: 5060
  registrationexpire: 600
  ringtoneEnabled: true
  ringtonePath: /usr/share/ring/ringtones/default.wav
  sameasLocal: true
  serviceRoute:
  srtp:
    enable: false
    keyExchange: sdes
    rtpFallback: false
  stunEnabled: false
  stunServer: stun.sflphone.org
  tls:
    calist:
    certificate:
    ciphers:
    enable: false
    method: TLSv1
    password:
    privateKey:
    requireCertif: true
    server:
    timeout: 2
    tlsPort: 5061
    verifyClient: true
    verifyServer: true
  type: SIP
  updateContact: false
  username:
  zrtp:
    displaySas: true
    displaySasOnce: false
    helloHashEnabled: true
    notSuppWarning: true
preferences:
  historyLimit: 30
  historyMaxCalls: 20
  md5Hash: false
  notifyMails: false
  order: Account:1334024356/Account:1334024061/
  portNum: 5060
  registrationexpire: 180
  searchBarDisplay: true
  zeroConfenable: false
  zoneToneChoice: North America
voipPreferences:
  playDtmf: true
  playTones: true
  pulseLength: 250
  symmetric: true
  zidFile: true
addressbook:
  business: true
  enabled: true
  home: true
  list:
  maxResults: 25
  mobile: true
  photo: true
hooks:
  numberAddPrefix:
  numberEnabled: false
  sipEnabled: false
  urlCommand: x-www-browser
  urlSipField: X-sflphone-url
audio:
  alsa:
    cardIn: 0
    cardOut: 0
    cardRing: 0
    plugin: default
    smplRate: 44100
  alwaysRecording: false
  audioApi: pulseaudio
  echoCancel: false
  echoDelayLength: 0
  echoTailLength: 100
  noiseReduce: true
  pulse:
    devicePlayback: alsa_output.pci-0000_00_1b.0.analog-stereo
    deviceRecord: alsa_input.pci-0000_00_1b.0.analog-stereo
    deviceRingtone: alsa_output.pci-0000_00_1b.0.analog-stereo
  recordPath:
  volumeMic: 100
  volumeSpkr: 100
shortcuts:
  hangUp:
  pickUp:
  popupWindow:
  toggleHold:
  togglePickupHangup:
...
