/* Generated by Together */

#include "AudioMixer2Channels.h"

AudioMixer2Channels::~AudioMixer2Channels()
{
}

void AudioMixer2Channels::run()
{
}

AudioMixer2Channels::AudioMixer2Channels(InternalBuffer* input1,  InternalBuffer* input2, OutputStream* output)
{
}

AudioMixer2Channels::AudioMixer2Channels()
{
}

