/* Generated by Together */

#include "AudioInput.h"
#include "TimeInfo.h"

TimeInfo AudioInput::fetchTimeInfo() const
{
  TimeInfo tmp(0);
  return tmp;
}

void AudioInput::putData(int16 *data, int size)
{ 
}

int AudioInput::fetchData(int16 *data) const 
{ 
  return 0;
}

AudioInput::AudioInput()
{
  
}

AudioInput::~AudioInput()
{
  
}

void AudioInput::putTimeInfo(TimeInfo* infos)
{
  
}
