/* Generated by Together */

#include "AudioSynch.h"

void AudioSynch::run()
{
  
}

AudioSynch::~AudioSynch()
{
  
}

AudioSynch::AudioSynch(InputStreams* inputStreams, InternalBuffer* video, InternalBuffer* audio)
{
  
}

AudioSynch::AudioSynch()
{
  
}

