/* Generated by Together */

#include "AudioOuput.h"


int AudioOuput::fetchData(int16 *data)
{ 
  return 0;
}

void AudioOuput::putData(int16 * data, int size)
{ 
  
}

AudioOuput::AudioOuput()
{
  
}

AudioOuput::~AudioOuput()
{
  
}
int AudioOuput::fetchData(char* data)
{
  return 0; 
}

void AudioOuput::putData(char * data, int size)
{ 
  
}
