/* Generated by Together */

#include "InputStreams.h"
#include "VideoInput.h"
#include "AudioInput.h"

InputStreams::InputStreams()
{
}

InputStreams::InputStreams(VideoInput* videoData, AudioInput* audioData)
{
}

InputStreams::~InputStreams()
{
}

const VideoInput* InputStreams::fetchVideoStream() const 
{
}

const AudioInput* InputStreams::fetchAudioStream() const 
{
}
