/* Generated by Together */

#include "InternalBuffer.h"

bool InternalBuffer::putData(char * data, int size)
{
	return true;	
}

int InternalBuffer::fetchData(char * data)
{
	return 0;
}

InternalBuffer::InternalBuffer()
{
	
}

InternalBuffer::~InternalBuffer()
{
	
}

void InternalBuffer::Init()
{
	
}
