/* Generated by Together */

#include "LocalAudioOuput.h"


int LocalAudioOuput::fetchData(int16 *data)
{ 
  return 0;
}

void LocalAudioOuput::putData(int16 * data, int size)
{ 
  
}

LocalAudioOuput::LocalAudioOuput()
{
  
}

LocalAudioOuput::~LocalAudioOuput()
{
  
}
