/* Generated by Together */

#ifndef LOCALAUDIOOUPUT_H
#define LOCALAUDIOOUPUT_H
#include "AudioOuput.h"

//! Local audio ouput
/*!
 * This class overloads the class AudioOuput to send the ouput directly to the sound device. This class is bound to change in a short future.
 */
class LocalAudioOuput : public AudioOuput {
public:

	//! Constructor
	/*!
	 * Initalizes the ouput device
	 */
    LocalAudioOuput();

    //! Destructor
    /*! Closes the device
     */
    virtual ~LocalAudioOuput();

    //! Changes the data in the buffer
    /*!
     * Writes the data to the audio device
     * \param data pointer to the new data
     * \param size the size of data
     */
    virtual void putData(int16 * data, int size);
    
private:
	
	//! Gets the data in the buffer
    /*!
     * This method is not used in this class
     */
    virtual int fetchData(int16 *data);
    
    //! Audio Device
    //AudioLayer* device;
};
#endif //LOCALAUDIOOUPUT_H
