/* Generated by Together */

#include "LocalVideoOuput.h"


int LocalVideoOuput::fetchData(char* data)
{
  return 0;
}

void LocalVideoOuput::putData(char * data, int size)
{ 
  
}

LocalVideoOuput::LocalVideoOuput()
{
  
}

LocalVideoOuput::~LocalVideoOuput()
{
  
}
