/* Generated by Together */

#include "NoSynch.h"


void NoSynch::run()
{ 
  
}

NoSynch::~NoSynch()
{
  
}

NoSynch::NoSynch(InputStreams* inputStreams, InternalBuffer* video, InternalBuffer* audio)
{
  
}

NoSynch::NoSynch()
{
  
}
