/* Generated by Together */

#include "StraightThrough_VT.h"
#include "InternalBuffer.h"
#include "OutputStream.h"

StraightThrough_VT::~StraightThrough_VT()
{
}

void StraightThrough_VT::run()
{ 
}

void StraightThrough_VT::pause()
{ 
}

void StraightThrough_VT::restart()
{ 
}

StraightThrough_VT::StraightThrough_VT(InternalBuffer* video,  OutputStream* output, CodecInfo* infos)
{
}

StraightThrough_VT::StraightThrough_VT()
{
}

