/* Generated by Together */

#ifndef TIMEINFO_H
#define TIMEINFO_H
class TimeInfo {
public:


    TimeInfo(int infos);

private:
    TimeInfo();
public:

    int getTemps();

private:
    int temps;
};
#endif //TIMEINFO_H
