/* Generated by Together */

#include "VideoMixer.h"
#include "InternalBuffer.h"
#include "OutputStream.h"
void VideoMixer::initBuffer(){ }
void VideoMixer::setCodecInfo(CodecInfo* infos){ }
void VideoMixer::resetBuffer(){ }
