/* Generated by Together */

#include "VideoMixer2Channels.h"
#include "OutputStream.h"

VideoMixer2Channels::~VideoMixer2Channels()
{
}

void VideoMixer2Channels::run()
{ 
}

void VideoMixer2Channels::pause()
{ 
}

void VideoMixer2Channels::restart()
{ 
}

VideoMixer2Channels::VideoMixer2Channels(InternalBuffer* video1, InternalBuffer* video2, OutputStream* output, CodecInfo* infos)
{
}

VideoMixer2Channels::VideoMixer2Channels()
{
}
