/* Generated by Together */

#include "VideoInput.h"
#include "TimeInfo.h"


int VideoInput::fetchData(char* data) const 
{ 
  return 0;
}

TimeInfo VideoInput::fetchTimeInfo() const 
{ 
  TimeInfo tmp(0);
  return tmp;
}

void VideoInput::putData(char * data, int size)
{ 

}

VideoInput::VideoInput()
{

}

VideoInput::~VideoInput()
{

}

void VideoInput::putTimeInfo(TimeInfo* infos)
{

}
