/* Generated by Together */

#include "VideoOutput.h"


int VideoOutput::fetchData(char* data)
{
  return 0;
}

void VideoOutput::putData(char * data, int size)
{ 
  
}

VideoOutput::VideoOutput()
{
  
}

VideoOutput::~VideoOutput()
{
  
}

int VideoOutput::fetchData(int16 *data)
{ 
  return 0;
}

void VideoOutput::putData(int16 * data, int size)
{ 
  
}

