=head1 NAME

ring-client-gnome - SIP and IAX2 compatible voice over IP softphone GTK+ client.

=head1 SYNOPSIS

ring-client-gnome

=head1 DESCRIPTION

Ring is meant to be a robust enterprise-class desktop phone. It provides functions like call transfer, call hold, multiple lines, multiple accounts support.
Ring audio layer is build upon a native ALSA interface and and a native PulseAudio interface.
B<ring-client-gnome> is a GTK+ client for Ring; it communicates with the core side through DBus. Ring package comes with the core, B<ringd>.

=head1 BUGS

Please report bugs at https://projects.savoirfairelinux.com/projects/sflphone/issues/new.

=head1 AUTHORS

B<ring-client-gnome> is developed in Montreal by Savoir-Faire Linux Inc.

This manual page was written by Emmanuel Milou <emmanuel.milou@savoirfairelinux.com>.

=head1 SEE ALSO

B<ringd>(1)

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 3 as published by the
Free Software Foundation.

On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL'.

=cut
