#!/bin/sh
# Copyright (C) 2005 Yan Morin <yan.morin@savoirfairelinux.com>
##
# Use the daemon to hangup all calls (with netcat)
# @author Yan Morin
##

. ./global

if [ ! -z `$pidof 'sflphoned'` ]; then
  callstring="stop sflphone\n"

  echo "Stopping sflphoned..."

  echo -en $callstring | $netcat

else
  echo "sflphoned is already stopped"
fi

