FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
        git \
        autoconf \
        automake \
        autopoint \
        cmake \
        libtool \
	libcanberra-gtk3-dev \
        libdbus-1-dev \
        libdbus-c++-dev \
        libupnp-dev \
        libgnutls28-dev \
        libebook1.2-dev \
        libclutter-gtk-1.0-dev \
        libclutter-1.0-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libnotify-dev \
        qtbase5-dev \
        qtmultimedia5-dev \
        qttools5-dev \
        qttools5-dev-tools \
        yasm \
        autotools-dev \
        gettext \
        libpulse-dev \
        libasound2-dev \
        libexpat1-dev \
        libyaml-cpp-dev \
        libboost-dev \
        libxext-dev \
        libxfixes-dev \
        libspeex-dev \
        libspeexdsp-dev \
        uuid-dev \
        libavcodec-dev \
        libavutil-dev \
        libavformat-dev \
        libswscale-dev \
        libavdevice-dev \
        libopus-dev \
        libudev-dev \
        libjsoncpp-dev \
        libnatpmp-dev \
        libappindicator3-dev \
        libqrencode-dev \
        libnm-glib-dev \
        libwebkit2gtk-4.0-dev \
        libcrypto++-dev \
        libva-dev \
        libvdpau-dev

# Tests framework
RUN apt-get install -y -o Acquire::Retries=10 \
        libcppunit-dev \
        sip-tester

RUN apt-get clean
