#!/bin/bash

gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -t string -s /desktop/gnome/url-handlers/tel/command "/usr/bin/sflphone-handler %s"
gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -s /desktop/gnome/url-handlers/tel/needs_terminal false -t bool
gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -t bool -s /desktop/gnome/url-handlers/tel/enabled true

gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -t string -s /desktop/gnome/url-handlers/callto/command "/usr/bin/sflphone-handler %s"
gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -s /desktop/gnome/url-handlers/callto/needs_terminal false -t bool
gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -t bool -s /desktop/gnome/url-handlers/callto/enabled true

gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -t string -s /desktop/gnome/url-handlers/sip/command "/usr/bin/sflphone-handler %s"
gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -s /desktop/gnome/url-handlers/sip/needs_terminal false -t bool
gconftool-2 --direct --config-source xml::/etc/gconf/gconf.xml.defaults -t bool -s /desktop/gnome/url-handlers/sip/enabled true

exit 0

