#define PULSEAUDIO_API_STR          "pulseaudio"
#define ALSA_API_STR                "alsa"
#define JACK_API_STR                "jack"
#define COREAUDIO_API_STR           "coreaudio"
#define PORTAUDIO_API_STR           "portaudio"
