######################################################################
# Automatically generated by qmake (2.00a) Wed Sep 21 08:58:47 2005
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += JPushButton.hpp \
           SFLPhoneWindow.hpp
SOURCES += main.cpp \
           JPushButton.cpp \
           SFLPhoneWindow.cpp
RESOURCES += sflphone.qrc
