######################################################################
# Automatically generated by qmake (2.01a) mer. f�vr. 18 11:08:41 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qdbus uitools debug

# Input
HEADERS += Account.h \
           AccountList.h \
           ConfigDialog.h \
           daemon_interface_p.h \
           daemon_interface_singleton.h \
           metatypes.h \
           sflphone_const.h
FORMS += ConfigDialog.ui
SOURCES += Account.cpp \
           AccountList.cpp \
           ConfigDialog.cpp \
           daemon_interface.cpp \
           daemon_interface_singleton.cpp \
           main.cpp \
           sflphone_const.cpp
TRANSLATIONS += config_en.ts
