/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_savoirfairelinux_sflphone_client_ManagerImpl */

#ifndef _Included_com_savoirfairelinux_sflphone_client_ManagerImpl
#define _Included_com_savoirfairelinux_sflphone_client_ManagerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    callVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_callVoid
  (JNIEnv *, jclass);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    getNewData
 * Signature: (ILjava/lang/String;)Lcom/savoirfairelinux/sflphone/client/Data;
 */
JNIEXPORT jobject JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_getNewData
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    getDataString
 * Signature: (Lcom/savoirfairelinux/sflphone/client/Data;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_getDataString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    getDataString2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_getDataString2
  (JNIEnv *, jclass);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    setSipLogLevel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_setSipLogLevel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_getJniString
  (JNIEnv *, jclass);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    outgoingCallN
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_outgoingCallN
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_savoirfairelinux_sflphone_client_ManagerImpl
 * Method:    initN
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_savoirfairelinux_sflphone_client_ManagerImpl_initN
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
