/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sflphone_service_SflCallManager */

#ifndef _Included_org_sflphone_service_SflCallManager
#define _Included_org_sflphone_service_SflCallManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sflphone_service_SflCallManager
 * Method:    outgoingCallN
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sflphone_service_SflCallManager_outgoingCallN
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
