/* Generated by Together */

#include "Brightness.h"


  Brightness::Brightness(){}

  Brightness::~Brightness(){}

  bool Brightness::increase(int value){

    return true;
  }

  bool Brightness::decrease(int value){

    return true;
  }

  bool Brightness::setTo(int value){

    return true;
  }

  bool Brightness::reset(){

    return true;
  }
  
  char* Brightness::GetBrightness(){

    return 0;
  }

