/* Generated by Together */

#include "Capture.h"
#include "CaptureMode.h"

  Capture::Capture(){}

  Capture::~Capture(){}

  void Capture::nextCaptureMode(){}

  bool Capture::forceCaptureMode(int captModePos){

    return true;
  }

  void Capture::createCaptureModesVector(){}

  bool Capture::decrease(int value){

    return true;
  }

  bool Capture::setTo(int value){

    return true;
  }

  bool Capture::reset(){

    return true;
  }

  char* Capture::GetCapture(){
    char* test;    

      *test = 't';

    return test;
  }

  bool Capture::increase(int value){

    return true;
  }
