/* Generated by Together */

#ifndef CAPTUREMODE_H
#define CAPTUREMODE_H


//! CaptureMode
/*!
 * This abstract class acts as an interface for multiple types of capture mode
 */
class CaptureMode {
public:

    //! Constructor
    CaptureMode();

    //! Destructor
    ~CaptureMode();

    //! The capture method
    /*!
     * Must be implemented by the child class
     */
    virtual char* capture()=0;
};
#endif //CAPTUREMODE_H

