/* Generated by Together */

#include "Colour.h"

  Colour::Colour(){}

  Colour::~Colour(){}

  bool Colour::increase(int value){

    return true;
  }

  bool Colour::decrease(int value){

    return true;
  }

  bool Colour::setTo(int value){

    return true;
  }

  bool Colour::reset(){

    return true;
  }
  
  char* Colour::GetColour(){

    return 0;
  }
