/* Generated by Together */

#include "Command.h"
#include "VideoDevice.h"

  //! A static pointer to access to the actual VideoDevice
//  VideoDevice* Command::videoDev = 0;

  Command::Command(){}

  Command::~Command(){}
