/* Generated by Together */

#ifndef COPYMODE_H
#define COPYMODE_H
#include "CaptureMode.h"

//! CopyMode
/*!
 * This class capture from the video source using a copy mode
 */
class CopyMode : public CaptureMode {
public:

    //! Constructor
    CopyMode();

    //! Destructor
    ~CopyMode();

    //! Method to capture from the video source
    /*!
     * \return a pointer to the captured data
     */
     char* capture();
};
#endif //COPYMODE_H
