/* Generated by Together */

#include "ReadMode.h"

  ReadMode::ReadMode(){}

  ReadMode::~ReadMode(){}

  char* ReadMode::capture(){
    char* test;    

      *test = 't';

    return test;
  }
