/* Generated by Together */

#include "Resolution.h"

  Resolution::Resolution(){}

  Resolution::~Resolution(){}

  bool Resolution::increase(int value){

    return true;
  }

  bool Resolution::decrease(int value){

    return true;
  }

  bool Resolution::setTo(int valueX, int valueY){

    return true;
  }

  bool Resolution::reset(){

    return true;
  }

  char* Resolution::GetResolution(){

    return 0;
  }
