/* Generated by Together */

#include "VideoDevice.h"

  VideoDevice::VideoDevice(){}

  VideoDevice::~VideoDevice(){}

  bool VideoDevice::CloseDevice(){

    return true;
  }

  bool VideoDevice::OpenDevice(){

    return true;
  }
  
  v4l2_format VideoDevice::getVideoFormat(){
    v4l2_format vF;
    
    return vF;
  }
  
  v4l2_capability VideoDevice::getVideoCapability(){
    v4l2_capability vC;

    return vC;
  }
  
  video_picture VideoDevice::getVideoPicture(){
    video_picture vP;

    return vP;
  }
  
  bool VideoDevice::setVideoFormat(v4l2_format& videoFormat){

    this->videoFormat = videoFormat;

    return true;
  }

  bool VideoDevice::setVideoCapability(v4l2_capability& videoCapability){

    this->videoCapability = videoCapability;

    return true;
  }
  
  bool VideoDevice::setVideoPicture(video_picture& videoPicture){

    this->videoPicture = videoPicture;

    return true;
  }
  
  char* VideoDevice::getName(){

    return 0;
  }

  int VideoDevice::getFileDescript(){

    return 0;
  }
