/* Generated by Together */

#include "VideoDeviceManager.h"
#include "VideoDevice.h"

  VideoDeviceManager* VideoDeviceManager::instance = 0;

  VideoDeviceManager* VideoDeviceManager::getInstance(){

    return instance; 
  }

  VideoDeviceManager::VideoDeviceManager(){}

  VideoDeviceManager::~VideoDeviceManager(){}

  bool VideoDeviceManager::changeDevice(VideoDevice* videoDev){

    return true;
  }

  VideoDevice* VideoDeviceManager::createDevice(char* srcName){
    
    return 0;
  }

  VideoDevice* VideoDeviceManager::getDevice(){

    return 0;
  }

  Command* VideoDeviceManager::getCommand(char* ref){
    
    return 0;
  }



