
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__contactmanager_glue_h__ADAPTOR_MARSHAL_H
#define __dbusxx__contactmanager_glue_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace org {
namespace sflphone {
namespace SFLphone {

class ContactManager
: public ::DBus::InterfaceAdaptor
{
public:

    ContactManager()
    : ::DBus::InterfaceAdaptor("org.sflphone.SFLphone.ContactManager")
    {
        register_method(ContactManager, getContacts, _getContacts_stub);
        register_method(ContactManager, setContacts, _setContacts_stub);
        register_method(ContactManager, setPresence, _setPresence_stub);
        register_method(ContactManager, setContactPresence, _setContactPresence_stub);
    }

    ::DBus::IntrospectedInterface* const introspect() const 
    {
        static ::DBus::IntrospectedArgument getContacts_args[] = 
        {
            { "accountID", "s", true },
            { "details", "a{ss}", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setContacts_args[] = 
        {
            { "accountID", "s", true },
            { "details", "a{ss}", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setPresence_args[] = 
        {
            { "accountID", "s", true },
            { "presence", "s", true },
            { "additionalInfo", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setContactPresence_args[] = 
        {
            { "accountID", "s", true },
            { "presence", "s", true },
            { "additionalInfo", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod ContactManager_methods[] = 
        {
            { "getContacts", getContacts_args },
            { "setContacts", setContacts_args },
            { "setPresence", setPresence_args },
            { "setContactPresence", setContactPresence_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod ContactManager_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty ContactManager_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface ContactManager_interface = 
        {
            "org.sflphone.SFLphone.ContactManager",
            ContactManager_methods,
            ContactManager_signals,
            ContactManager_properties
        };
        return &ContactManager_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::map< ::DBus::String, ::DBus::String > getContacts( const ::DBus::String& accountID ) = 0;
    virtual void setContacts( const ::DBus::String& accountID, const std::map< ::DBus::String, ::DBus::String >& details ) = 0;
    virtual void setPresence( const ::DBus::String& accountID, const ::DBus::String& presence, const ::DBus::String& additionalInfo ) = 0;
    virtual void setContactPresence( const ::DBus::String& accountID, const ::DBus::String& presence, const ::DBus::String& additionalInfo ) = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _getContacts_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        std::map< ::DBus::String, ::DBus::String > argout1 = getContacts(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _setContacts_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        std::map< ::DBus::String, ::DBus::String > argin2; ri >> argin2;
        setContacts(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _setPresence_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        ::DBus::String argin3; ri >> argin3;
        setPresence(argin1, argin2, argin3);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _setContactPresence_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        ::DBus::String argin3; ri >> argin3;
        setContactPresence(argin1, argin2, argin3);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

} } } 
#endif//__dbusxx__contactmanager_glue_h__ADAPTOR_MARSHAL_H
