
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__instance_glue_h__ADAPTOR_MARSHAL_H
#define __dbusxx__instance_glue_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace org {
namespace sflphone {
namespace SFLphone {

class Instance
: public ::DBus::InterfaceAdaptor
{
public:

    Instance()
    : ::DBus::InterfaceAdaptor("org.sflphone.SFLphone.Instance")
    {
        register_method(Instance, Register, _Register_stub);
        register_method(Instance, Unregister, _Unregister_stub);
        register_method(Instance, getRegistrationCount, _getRegistrationCount_stub);
    }

    ::DBus::IntrospectedInterface* const introspect() const 
    {
        static ::DBus::IntrospectedArgument Register_args[] = 
        {
            { "pid", "i", true },
            { "name", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Unregister_args[] = 
        {
            { "pid", "i", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getRegistrationCount_args[] = 
        {
            { "count", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod Instance_methods[] = 
        {
            { "Register", Register_args },
            { "Unregister", Unregister_args },
            { "getRegistrationCount", getRegistrationCount_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Instance_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Instance_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Instance_interface = 
        {
            "org.sflphone.SFLphone.Instance",
            Instance_methods,
            Instance_signals,
            Instance_properties
        };
        return &Instance_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void Register( const ::DBus::Int32& pid, const ::DBus::String& name ) = 0;
    virtual void Unregister( const ::DBus::Int32& pid ) = 0;
    virtual ::DBus::Int32 getRegistrationCount(  ) = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Register_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Int32 argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        Register(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _Unregister_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Int32 argin1; ri >> argin1;
        Unregister(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _getRegistrationCount_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Int32 argout1 = getRegistrationCount();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } } 
#endif//__dbusxx__instance_glue_h__ADAPTOR_MARSHAL_H
