/* Generated by Together */

#include "MemKey.h"

MemKey::MemKey(int size, char* description)
{
}

MemKey::~MemKey()
{
}

int MemKey::getKey()
{
	return 0;
}

const char * MemKey::getDescription() const 
{
	return 0;
}

int MemKey::getIndex()
{
	return 0;
}

void MemKey::setIndex(int index)
{ 
}

MemKey::MemKey(MemKey* key)
{	
}

MemKey::MemKey(MemKey& key)
{
}

int MemKey::getSize()
{
	return 0;
}

char * MemKey::serialize()
{
	return 0;
}

MemKey::MemKey()
{
	
}

MemKey::MemKey(char* serializedData)
{
}
