/* Generated by Together */

#include "MemSorter.h"
bool MemSorter::operator()(MemKey* key1, MemKey* key2)
{
	return false;
	
	//TODO: Ref.: http://en.wikipedia.org/wiki/Function_object#Functors_in_C_and_C.2B.2B
}
