/* Generated by Together */

#ifndef MEMSORTER_H
#define MEMSORTER_H
#include "MemKey.h"

//! Acts as a functor to sort the MemKeys
class MemSorter {
public:

	//! The comparaision operator
    bool operator()(MemKey* key1, MemKey* key2);
    
};
#endif //MEMSORTER_H
