/* Generated by Together */

#include "MemSpace.h"
#include "MemKey.h"
#include "MemData.h"

MemSpace::MemSpace()
{
}

MemSpace::MemSpace(MemKey* key)
{
}

MemKey* MemSpace::getKey()
{
}

bool MemSpace::putData(void * Data, int size)
{
	return false;
}

MemData* MemSpace::fetchData()
{
}

MemSpace::MemSpace(MemSpace* space)
{
}

MemSpace::MemSpace(MemSpace& space)
{
}

MemSpace::~MemSpace()
{
}

void MemSpace::readSpace(MemData* data)
{
}

void MemSpace::writeSpace(char * data, int size)
{
}
