/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -c ConfigurationManagerInterface -i dbus/metatypes.h -p configurationmanager_dbus_interface /home/emmanuel/sflphone/sflphone-client-kde/src/dbus/configurationmanager-introspec.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CONFIGURATIONMANAGER_DBUS_INTERFACE_H_1271787581
#define CONFIGURATIONMANAGER_DBUS_INTERFACE_H_1271787581

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "dbus/metatypes.h"

/*
 * Proxy class for interface org.sflphone.SFLphone.ConfigurationManager
 */
class ConfigurationManagerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.sflphone.SFLphone.ConfigurationManager"; }

public:
    ConfigurationManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ConfigurationManagerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> addAccount(MapStringString details)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(details);
        return asyncCallWithArgumentList(QLatin1String("addAccount"), argumentList);
    }

    inline QDBusPendingReply<> deleteAllCredential(const QString &accountID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID);
        return asyncCallWithArgumentList(QLatin1String("deleteAllCredential"), argumentList);
    }

    inline QDBusPendingReply<> enableStatusIcon(const QString &value)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(value);
        return asyncCallWithArgumentList(QLatin1String("enableStatusIcon"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getAccountDetails(const QString &accountID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID);
        return asyncCallWithArgumentList(QLatin1String("getAccountDetails"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getAccountList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAccountList"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getActiveCodecList(const QString &accountID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID);
        return asyncCallWithArgumentList(QLatin1String("getActiveCodecList"), argumentList);
    }

    inline QDBusPendingReply<QString> getAddrFromInterfaceName(const QString &interface)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(interface);
        return asyncCallWithArgumentList(QLatin1String("getAddrFromInterfaceName"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getAddressbookList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAddressbookList"), argumentList);
    }

    inline QDBusPendingReply<MapStringInt> getAddressbookSettings()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAddressbookSettings"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getAllIpInterface()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAllIpInterface"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getAllIpInterfaceByName()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAllIpInterfaceByName"), argumentList);
    }

    inline QDBusPendingReply<int> getAudioDeviceIndex(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(name);
        return asyncCallWithArgumentList(QLatin1String("getAudioDeviceIndex"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getAudioInputDeviceList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAudioInputDeviceList"), argumentList);
    }

    inline QDBusPendingReply<int> getAudioManager()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAudioManager"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getAudioOutputDeviceList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getAudioOutputDeviceList"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getCodecDetails(int payload)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(payload);
        return asyncCallWithArgumentList(QLatin1String("getCodecDetails"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getCodecList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getCodecList"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getCredential(const QString &accountID, int index)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID) << qVariantFromValue(index);
        return asyncCallWithArgumentList(QLatin1String("getCredential"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getCurrentAudioDevicesIndex()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getCurrentAudioDevicesIndex"), argumentList);
    }

    inline QDBusPendingReply<QString> getCurrentAudioOutputPlugin()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getCurrentAudioOutputPlugin"), argumentList);
    }

    inline QDBusPendingReply<int> getDialpad()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getDialpad"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getHistory()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getHistory"), argumentList);
    }

    inline QDBusPendingReply<QString> getHistoryEnabled()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getHistoryEnabled"), argumentList);
    }

    inline QDBusPendingReply<int> getHistoryLimit()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getHistoryLimit"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getHookSettings()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getHookSettings"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getInputAudioPluginList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getInputAudioPluginList"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getIp2IpDetails()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getIp2IpDetails"), argumentList);
    }

    inline QDBusPendingReply<int> getMailNotify()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getMailNotify"), argumentList);
    }

    inline QDBusPendingReply<int> getNotify()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getNotify"), argumentList);
    }

    inline QDBusPendingReply<int> getNumberOfCredential(const QString &accountID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID);
        return asyncCallWithArgumentList(QLatin1String("getNumberOfCredential"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getOutputAudioPluginList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getOutputAudioPluginList"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getPlaybackDeviceList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getPlaybackDeviceList"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getRecordDeviceList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getRecordDeviceList"), argumentList);
    }

    inline QDBusPendingReply<QString> getRecordPath()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getRecordPath"), argumentList);
    }

    inline QDBusPendingReply<QString> getRingtoneChoice()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getRingtoneChoice"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getRingtoneList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getRingtoneList"), argumentList);
    }

    inline QDBusPendingReply<int> getSearchbar()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getSearchbar"), argumentList);
    }

    inline QDBusPendingReply<MapStringInt> getShortcuts()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getShortcuts"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getSupportedTlsMethod()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getSupportedTlsMethod"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getTlsSettings(const QString &accountID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID);
        return asyncCallWithArgumentList(QLatin1String("getTlsSettings"), argumentList);
    }

    inline QDBusPendingReply<MapStringString> getTlsSettingsDefault()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getTlsSettingsDefault"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getToneLocaleList()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getToneLocaleList"), argumentList);
    }

    inline QDBusPendingReply<QString> getVersion()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getVersion"), argumentList);
    }

    inline QDBusPendingReply<int> getVolumeControls()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getVolumeControls"), argumentList);
    }

    inline QDBusPendingReply<int> getWindowHeight()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getWindowHeight"), argumentList);
    }

    inline QDBusPendingReply<int> getWindowPositionX()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getWindowPositionX"), argumentList);
    }

    inline QDBusPendingReply<int> getWindowPositionY()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getWindowPositionY"), argumentList);
    }

    inline QDBusPendingReply<int> getWindowWidth()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getWindowWidth"), argumentList);
    }

    inline QDBusPendingReply<int> isIax2Enabled()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isIax2Enabled"), argumentList);
    }

    inline QDBusPendingReply<bool> isMd5CredentialHashing()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isMd5CredentialHashing"), argumentList);
    }

    inline QDBusPendingReply<int> isRingtoneEnabled()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isRingtoneEnabled"), argumentList);
    }

    inline QDBusPendingReply<int> isStartHidden()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isStartHidden"), argumentList);
    }

    inline QDBusPendingReply<QString> isStatusIconEnabled()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isStatusIconEnabled"), argumentList);
    }

    inline QDBusPendingReply<int> popupMode()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("popupMode"), argumentList);
    }

    inline QDBusPendingReply<> removeAccount(const QString &accoundID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accoundID);
        return asyncCallWithArgumentList(QLatin1String("removeAccount"), argumentList);
    }

    inline QDBusPendingReply<> ringtoneEnabled()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ringtoneEnabled"), argumentList);
    }

    inline QDBusPendingReply<> sendRegister(const QString &accountID, int expire)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID) << qVariantFromValue(expire);
        return asyncCallWithArgumentList(QLatin1String("sendRegister"), argumentList);
    }

    inline QDBusPendingReply<> setAccountDetails(const QString &accountID, MapStringString details)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID) << qVariantFromValue(details);
        return asyncCallWithArgumentList(QLatin1String("setAccountDetails"), argumentList);
    }

    inline QDBusPendingReply<> setAccountsOrder(const QString &order)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(order);
        return asyncCallWithArgumentList(QLatin1String("setAccountsOrder"), argumentList);
    }

    inline QDBusPendingReply<> setActiveCodecList(const QStringList &list, const QString &accountID)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(list) << qVariantFromValue(accountID);
        return asyncCallWithArgumentList(QLatin1String("setActiveCodecList"), argumentList);
    }

    inline QDBusPendingReply<> setAddressbookList(const QStringList &settings)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(settings);
        return asyncCallWithArgumentList(QLatin1String("setAddressbookList"), argumentList);
    }

    inline QDBusPendingReply<> setAddressbookSettings(MapStringInt settings)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(settings);
        return asyncCallWithArgumentList(QLatin1String("setAddressbookSettings"), argumentList);
    }

    inline QDBusPendingReply<> setAudioInputDevice(int index)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(index);
        return asyncCallWithArgumentList(QLatin1String("setAudioInputDevice"), argumentList);
    }

    inline QDBusPendingReply<> setAudioManager(int api)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(api);
        return asyncCallWithArgumentList(QLatin1String("setAudioManager"), argumentList);
    }

    inline QDBusPendingReply<> setAudioOutputDevice(int index)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(index);
        return asyncCallWithArgumentList(QLatin1String("setAudioOutputDevice"), argumentList);
    }

    inline QDBusPendingReply<> setCredential(const QString &accountID, int index, MapStringString credentialInformation)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID) << qVariantFromValue(index) << qVariantFromValue(credentialInformation);
        return asyncCallWithArgumentList(QLatin1String("setCredential"), argumentList);
    }

    inline QDBusPendingReply<> setDialpad(bool display)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(display);
        return asyncCallWithArgumentList(QLatin1String("setDialpad"), argumentList);
    }

    inline QDBusPendingReply<> setHistory(MapStringString entries)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(entries);
        return asyncCallWithArgumentList(QLatin1String("setHistory"), argumentList);
    }

    inline QDBusPendingReply<> setHistoryEnabled()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("setHistoryEnabled"), argumentList);
    }

    inline QDBusPendingReply<> setHistoryLimit(int days)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(days);
        return asyncCallWithArgumentList(QLatin1String("setHistoryLimit"), argumentList);
    }

    inline QDBusPendingReply<> setHookSettings(MapStringString settings)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(settings);
        return asyncCallWithArgumentList(QLatin1String("setHookSettings"), argumentList);
    }

    inline QDBusPendingReply<> setInputAudioPlugin(const QString &audioPlugin)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(audioPlugin);
        return asyncCallWithArgumentList(QLatin1String("setInputAudioPlugin"), argumentList);
    }

    inline QDBusPendingReply<> setIp2IpDetails(MapStringString details)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(details);
        return asyncCallWithArgumentList(QLatin1String("setIp2IpDetails"), argumentList);
    }

    inline QDBusPendingReply<> setMailNotify()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("setMailNotify"), argumentList);
    }

    inline QDBusPendingReply<> setMd5CredentialHashing(bool enabled)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(enabled);
        return asyncCallWithArgumentList(QLatin1String("setMd5CredentialHashing"), argumentList);
    }

    inline QDBusPendingReply<> setNotify()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("setNotify"), argumentList);
    }

    inline QDBusPendingReply<> setNumberOfCredential(const QString &accountID, int number)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID) << qVariantFromValue(number);
        return asyncCallWithArgumentList(QLatin1String("setNumberOfCredential"), argumentList);
    }

    inline QDBusPendingReply<> setOutputAudioPlugin(const QString &audioPlugin)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(audioPlugin);
        return asyncCallWithArgumentList(QLatin1String("setOutputAudioPlugin"), argumentList);
    }

    inline QDBusPendingReply<> setRecordPath(const QString &rec)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(rec);
        return asyncCallWithArgumentList(QLatin1String("setRecordPath"), argumentList);
    }

    inline QDBusPendingReply<> setRingtoneChoice(const QString &tone)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(tone);
        return asyncCallWithArgumentList(QLatin1String("setRingtoneChoice"), argumentList);
    }

    inline QDBusPendingReply<> setSearchbar()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("setSearchbar"), argumentList);
    }

    inline QDBusPendingReply<> setShortcuts(MapStringInt shortcutsMap)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(shortcutsMap);
        return asyncCallWithArgumentList(QLatin1String("setShortcuts"), argumentList);
    }

    inline QDBusPendingReply<> setTlsSettings(const QString &accountID, MapStringString details)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(accountID) << qVariantFromValue(details);
        return asyncCallWithArgumentList(QLatin1String("setTlsSettings"), argumentList);
    }

    inline QDBusPendingReply<> setVolumeControls(bool display)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(display);
        return asyncCallWithArgumentList(QLatin1String("setVolumeControls"), argumentList);
    }

    inline QDBusPendingReply<> setWindowHeight(int height)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(height);
        return asyncCallWithArgumentList(QLatin1String("setWindowHeight"), argumentList);
    }

    inline QDBusPendingReply<> setWindowPositionX(int posX)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(posX);
        return asyncCallWithArgumentList(QLatin1String("setWindowPositionX"), argumentList);
    }

    inline QDBusPendingReply<> setWindowPositionY(int posY)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(posY);
        return asyncCallWithArgumentList(QLatin1String("setWindowPositionY"), argumentList);
    }

    inline QDBusPendingReply<> setWindowWidth(int width)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(width);
        return asyncCallWithArgumentList(QLatin1String("setWindowWidth"), argumentList);
    }

    inline QDBusPendingReply<> startHidden()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("startHidden"), argumentList);
    }

    inline QDBusPendingReply<> switchPopupMode()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("switchPopupMode"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void accountsChanged();
    void errorAlert(int code);
};

namespace org {
  namespace sflphone {
    namespace SFLphone {
      typedef ::ConfigurationManagerInterface ConfigurationManager;
    }
  }
}
#endif
