/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -c InstanceInterface -i dbus/metatypes.h -p instance_dbus_interface /home/emmanuel/sflphone/sflphone-client-kde/src/dbus/instance-introspec.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "instance_dbus_interface.h"

/*
 * Implementation of interface class InstanceInterface
 */

InstanceInterface::InstanceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

InstanceInterface::~InstanceInterface()
{
}


#include "instance_dbus_interface.moc"
