// This file is generated by kconfig_compiler from sflphone-client-kde.kcfg.
// All changes you do to this file will be lost.

#include "kcfg_settings.h"

ConfigurationSkeletonBase::ConfigurationSkeletonBase(  )
  : KConfigSkeleton( QLatin1String( "ConfigDialogKDE" ) )
{
  setCurrentGroup( QLatin1String( "main" ) );

  KConfigSkeleton::ItemInt  *itemSIPPort;
  itemSIPPort = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "SIPPort" ), mSIPPort,  1025  );
  itemSIPPort->setMinValue( 1025 );
  itemSIPPort->setMaxValue( 65536 );
  addItem( itemSIPPort, QLatin1String( "SIPPort" ) );
  KConfigSkeleton::ItemBool  *itemEnableHistory;
  itemEnableHistory = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "enableHistory" ), mEnableHistory );
  addItem( itemEnableHistory, QLatin1String( "enableHistory" ) );
  KConfigSkeleton::ItemInt  *itemHistoryMax;
  itemHistoryMax = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "historyMax" ), mHistoryMax,  30  );
  itemHistoryMax->setMinValue( 1 );
  itemHistoryMax->setMaxValue( 99 );
  addItem( itemHistoryMax, QLatin1String( "historyMax" ) );
  KConfigSkeleton::ItemBool  *itemNotifOnCalls;
  itemNotifOnCalls = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "notifOnCalls" ), mNotifOnCalls );
  addItem( itemNotifOnCalls, QLatin1String( "notifOnCalls" ) );
  KConfigSkeleton::ItemBool  *itemNotifOnMessages;
  itemNotifOnMessages = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "notifOnMessages" ), mNotifOnMessages );
  addItem( itemNotifOnMessages, QLatin1String( "notifOnMessages" ) );
  KConfigSkeleton::ItemBool  *itemDisplayOnStart;
  itemDisplayOnStart = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "displayOnStart" ), mDisplayOnStart );
  addItem( itemDisplayOnStart, QLatin1String( "displayOnStart" ) );
  KConfigSkeleton::ItemBool  *itemDisplayOnCalls;
  itemDisplayOnCalls = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "displayOnCalls" ), mDisplayOnCalls );
  addItem( itemDisplayOnCalls, QLatin1String( "displayOnCalls" ) );
  QList<KConfigSkeleton::ItemEnum::Choice2> valuesinterface;
  {
    KConfigSkeleton::ItemEnum::Choice2 choice;
    choice.name = QLatin1String("ALSA");
    valuesinterface.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice2 choice;
    choice.name = QLatin1String("PulseAudio");
    valuesinterface.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemInterface;
  itemInterface = new KConfigSkeleton::ItemEnum( currentGroup(), QLatin1String( "interface" ), mInterface, valuesinterface );
  addItem( itemInterface, QLatin1String( "interface" ) );
  KConfigSkeleton::ItemBool  *itemEnableRingtones;
  itemEnableRingtones = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "enableRingtones" ), mEnableRingtones );
  addItem( itemEnableRingtones, QLatin1String( "enableRingtones" ) );
  KConfigSkeleton::ItemPath  *itemRingtone;
  itemRingtone = new KConfigSkeleton::ItemPath( currentGroup(), QLatin1String( "ringtone" ), mRingtone );
  addItem( itemRingtone, QLatin1String( "ringtone" ) );
  KConfigSkeleton::ItemString  *itemAlsaPlugin;
  itemAlsaPlugin = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "alsaPlugin" ), mAlsaPlugin );
  addItem( itemAlsaPlugin, QLatin1String( "alsaPlugin" ) );
  KConfigSkeleton::ItemInt  *itemAlsaInputDevice;
  itemAlsaInputDevice = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "alsaInputDevice" ), mAlsaInputDevice );
  addItem( itemAlsaInputDevice, QLatin1String( "alsaInputDevice" ) );
  KConfigSkeleton::ItemInt  *itemAlsaOutputDevice;
  itemAlsaOutputDevice = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "alsaOutputDevice" ), mAlsaOutputDevice );
  addItem( itemAlsaOutputDevice, QLatin1String( "alsaOutputDevice" ) );
  KConfigSkeleton::ItemBool  *itemPulseAudioVolumeAlter;
  itemPulseAudioVolumeAlter = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "pulseAudioVolumeAlter" ), mPulseAudioVolumeAlter );
  addItem( itemPulseAudioVolumeAlter, QLatin1String( "pulseAudioVolumeAlter" ) );
  KConfigSkeleton::ItemBool  *itemEnableAddressBook;
  itemEnableAddressBook = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "enableAddressBook" ), mEnableAddressBook );
  addItem( itemEnableAddressBook, QLatin1String( "enableAddressBook" ) );
  KConfigSkeleton::ItemInt  *itemMaxResults;
  itemMaxResults = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "maxResults" ), mMaxResults );
  addItem( itemMaxResults, QLatin1String( "maxResults" ) );
  KConfigSkeleton::ItemBool  *itemDisplayPhoto;
  itemDisplayPhoto = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "displayPhoto" ), mDisplayPhoto );
  addItem( itemDisplayPhoto, QLatin1String( "displayPhoto" ) );
  KConfigSkeleton::ItemBool  *itemBusiness;
  itemBusiness = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "business" ), mBusiness );
  addItem( itemBusiness, QLatin1String( "business" ) );
  KConfigSkeleton::ItemBool  *itemMobile;
  itemMobile = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "mobile" ), mMobile );
  addItem( itemMobile, QLatin1String( "mobile" ) );
  KConfigSkeleton::ItemBool  *itemHome;
  itemHome = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "home" ), mHome );
  addItem( itemHome, QLatin1String( "home" ) );
  KConfigSkeleton::ItemPath  *itemDestinationFolder;
  itemDestinationFolder = new KConfigSkeleton::ItemPath( currentGroup(), QLatin1String( "destinationFolder" ), mDestinationFolder );
  addItem( itemDestinationFolder, QLatin1String( "destinationFolder" ) );
  KConfigSkeleton::ItemBool  *itemEnableHooksSIP;
  itemEnableHooksSIP = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "enableHooksSIP" ), mEnableHooksSIP );
  addItem( itemEnableHooksSIP, QLatin1String( "enableHooksSIP" ) );
  KConfigSkeleton::ItemBool  *itemEnableHooksIAX;
  itemEnableHooksIAX = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "enableHooksIAX" ), mEnableHooksIAX );
  addItem( itemEnableHooksIAX, QLatin1String( "enableHooksIAX" ) );
  KConfigSkeleton::ItemString  *itemHooksSIPHeader;
  itemHooksSIPHeader = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "hooksSIPHeader" ), mHooksSIPHeader );
  addItem( itemHooksSIPHeader, QLatin1String( "hooksSIPHeader" ) );
  KConfigSkeleton::ItemString  *itemHooksCommand;
  itemHooksCommand = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "hooksCommand" ), mHooksCommand );
  addItem( itemHooksCommand, QLatin1String( "hooksCommand" ) );
  KConfigSkeleton::ItemBool  *itemAddPrefix;
  itemAddPrefix = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "addPrefix" ), mAddPrefix );
  addItem( itemAddPrefix, QLatin1String( "addPrefix" ) );
  KConfigSkeleton::ItemString  *itemPrepend;
  itemPrepend = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "prepend" ), mPrepend );
  addItem( itemPrepend, QLatin1String( "prepend" ) );
}

ConfigurationSkeletonBase::~ConfigurationSkeletonBase()
{
}

